FROM php:8.4-cli-trixie

ARG USER_ID=1000
ARG GROUP_ID=1000

ENV PHP_CLI_SERVER_WORKERS=4

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libzip-dev \
        libpng-dev \
        libjpeg62-turbo-dev \
        libwebp-dev \
        libfreetype6-dev \
        ffmpeg \
    && docker-php-ext-configure gd \
        --with-freetype \
        --with-jpeg \
        --with-webp \
    && docker-php-ext-install \
        pdo_mysql \
        zip \
        bcmath \
        gd \
        exif \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN groupmod -g ${GROUP_ID} www-data \
    && usermod -u ${USER_ID} www-data

WORKDIR /app

COPY --chown=www-data:www-data . .

RUN composer install

USER www-data

EXPOSE 8000

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]